<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Testing.Toolkit.Tests</RootNamespace>
		<AssemblyName>Testing.Toolkit.Tests</AssemblyName>
		<IsPackable>false</IsPackable>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Testing.Toolkit\Toolkit.csproj" />
	</ItemGroup>
</Project>
